name: Delete Branch & Create Branch

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 3 * * *'

jobs:
  merge-branch:
    # needs: create-branch
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          ref: stage

      - name: Get Current Release Branch
        id: release
        run: echo "::set-output name=branch::$(date +'release/v%Y%m%d')"

      - name: Echo Release Branch
        run: echo ${{ steps.release.outputs.branch }}

      - name: Create PR to stage1
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: Update report
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: ${{ steps.release.outputs.branch }}
          base: stage
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          milestone: 1
          draft: false
