name: Delete Branch & Create Branch

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      # 해당 저장소의 코드를 가져옵니다.
      - name: Git checkout
        uses: actions/checkout@v3
      # 해당 브랜치를 삭제한다.
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: stage

  create-branch:
    needs: delete-branch
    runs-on: ubuntu-latest
    steps:
      # 해당 저장소의 코드를 가져옵니다.
      - name: Git checkout
        uses: actions/checkout@v3

      # 해당 브랜치를 생성한다.
      - name: create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          branch: stage

  stage-pr-branch:
    needs: create-branch
    runs-on: ubuntu-latest

    steps:
      # 현재 날짜를 얻어와서 릴리즈 브랜치명으로 변경
      - name: Get Current Release Branch
        id: release
        run: echo "::set-output name=branch::$(date +'release/v%Y%m%d')"

      # 릴리즈 브랜치명 출력
      - name: Echo Release Branch
        run: echo ${{ steps.release.outputs.branch }}

      # 해당 저장소의 코드를 가져옵니다.(PR과 상관없는 브랜치로 checkout, 안그럴경우 액션 오류)
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          ref: master

      # stage 브랜치 머지
      - name: Create PR to stage
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          source_branch: ${{ steps.release.outputs.branch }}
          target_branch: stage
          title: ${{ steps.release.outputs.branch }} pull request
          body: '**Automated pull request**'
          label: frontend
          new_string: '** Automatic pull request**'
          get_diff: true
          allow_no_diff: true

      # main 브랜치 머지
      - name: Create PR to main
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          source_branch: ${{ steps.release.outputs.branch }}
          target_branch: main
          title: ${{ steps.release.outputs.branch }} pull request
          body: '**Automated pull request**'
          label: frontend
          new_string: '** Automatic pull request**'
          get_diff: true
          allow_no_diff: true
