name: Delete Branch & Create Branch

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 3 * * *'

jobs:
  merge-branch:
    # needs: create-branch
    runs-on: ubuntu-latest

    steps:
      - name: Get Current Release Branch
        id: release
        run: echo "::set-output name=branch::$(date +'release/v%Y%m%d')"

      - name: Echo Release Branch
        run: echo ${{ steps.release.outputs.branch }}

      - name: Git checkout
        uses: actions/checkout@v3

      - name: Create PR to stage
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          source_branch: ${{ steps.release.outputs.branch }}
          target_branch: stage
          title: My pull request
          body: '**Automated pull request**'
          label: enhancement
          draft: true
          old_string: '<!-- Add your description here -->'
          new_string: '** Automatic pull request**'
          get_diff: true
          allow_no_diff: false
