name: Delete Branch & Create Branch

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 3 * * *'

jobs:
  merge-branch:
    # needs: create-branch
    runs-on: ubuntu-latest

    steps:
      - name: Get Current Release Branch
        id: release
        run: echo "::set-output name=branch::$(date +'release/v%Y%m%d')"

      - name: Echo Release Branch
        run: echo ${{ steps.release.outputs.branch }}

      - name: Git checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.release.outputs.branch }}

      - name: Create PR to stage
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          head: ${{ github.ref }}
          base: stage
          title: ${{ github.event.head_commit.message }}
