name: Delete Branch & Create Branch

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 3 * * *'

jobs:
  stage-pr-branch:
    # needs: create-branch
    runs-on: ubuntu-latest

    steps:
      - name: Get Current Release Branch
        id: release
        run: echo "::set-output name=branch::$(date +'release/v%Y%m%d')"

      - name: Echo Release Branch
        run: echo ${{ steps.release.outputs.branch }}

      - name: Git checkout
        uses: actions/checkout@v3

      - name: Create PR to stage
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          source_branch: ${{ steps.release.outputs.branch }}
          target_branch: stage
          title: ${{ steps.release.outputs.branch }} pull request
          body: '**Automated pull request**'
          label: frontend
          new_string: '** Automatic pull request**'
          get_diff: true
          allow_no_diff: true

      - name: Create PR to master
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          source_branch: ${{ steps.release.outputs.branch }}
          target_branch: master
          title: ${{ steps.release.outputs.branch }} pull request
          body: '**Automated pull request**'
          label: frontend
          new_string: '** Automatic pull request**'
          get_diff: true
          allow_no_diff: true
