name: Delete Branch & Create Branch

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 3 * * *'

jobs:
  merge-branch:
    # needs: create-branch
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Get Current Release Branch
        id: release
        run: echo "::set-output name=branch::$(date +'release/v%Y%m%d')"

      - name: Echo Release Branch
        run: echo ${{ steps.release.outputs.branch }}
