name: Delete Branch & Create Branch

on:
  schedule:
    - cron: '0 21 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    # 해당 브랜치가 생성되어 있는지를 확인한다.
    # if: github.ref == 'refs/heads/stage'
    steps:
      # 해당 저장소의 코드를 가져옵니다.
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 해당 브랜치를 삭제한다.
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: stage

  create-branch:
    needs: delete-branch
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        with:
          branch: stage
