name: Delete Branch & Create Branch

on:
  schedule:
    - cron: '0 21 * * *'
  push:
    branches:
      - '*'

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    # if:
    #   # 해당 브랜치가 생성되어 있는지를 확인한다.
    #   contains(github.ref, 'stage')
    steps:
      # 해당 저장소의 코드를 가져옵니다.
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Check if branch exists
        # 해당 브랜치가 생성되어 있는지를 확인 후 삭제한다.
        run: |
          branch_name="remotes/origin/stage"
          if git rev-parse --verify "$branch_name" > /dev/null 2>&1; then
            echo "Branch $branch_name exists. Deleting..."
            git push origin --delete "$branch_name"
          else
            echo "Branch $branch_name does not exist."
            echo "$github.ref"
          fi

  create-branch:
    needs: delete-branch
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: stage
